# Generated by Django 4.2.7 on 2023-12-03 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('not_sent', 'Not Sent')], default='not_sent', max_length=50, verbose_name='memo status')),
                ('importance', models.CharField(choices=[('high', 'High'), ('middle', 'Middle'), ('low', 'Low')], max_length=50, null=True, verbose_name='memo importance level')),
                ('theme', models.CharField(max_length=200, null=True, verbose_name='theme')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='description')),
                ('time_to_send', models.DateTimeField(verbose_name='time to send')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Memo',
                'verbose_name_plural': 'Memos',
            },
        ),
    ]
